#!/bin/sh
echo Spio12345 | sudo -S commandsudo docker-compose stop app-node
echo Spio12345 | sudo -S commandsudo docker-compose build app-node
echo Spio12345 | sudo -S commandsudo docker-compose up -d app-node
